POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vblNlbnNlUG9ldHJ5QGdtYWlsLmNvLnVrIiwiaWQiOjQsImlhdCI6MTY1NDcyMzE0NH0.uABM-zqj4ncEsykaG9dEiSv1RV3y2MsV56cIG4rOvUE

{
"title": "Middleware Blog post",
"author": "Middleware Authorization: ",
"url": "https://middlewaretoken.com/blog/token-authorized",
"likes": 23
}