PUT http://localhost:3003/api/users/pablo@gmail.com
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vblNlbnNlUG9ldHJ5QGVtYWlsLmNvLnVrIiwiaWQiOjEsImlhdCI6MTY1NTI0MTY3OH0.RpV7YfKyXCgYdIcXdIWB4f_4FuZ2EMok95i25VCr-lI

{
  "disabled": false
}