PUT http://localhost:3003/api/users/pablo@gmail.com
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGJsb2dzLmNvbSIsImlkIjozLCJzZXNzaW9uVG9rZW4iOiI3MWNhOTNlZmJjN2FmZGQxMTUyZTdlMjM4NWRmMmQ0YjExY2VkNTk1NGU5Y2E1OTFjYzEyZjgzN2FlYzMxMTk3NjA2YjM1OWFmMDI2OTE3OTQyNjQzMjg1ZTk0Yjg4NmViM2ZhZTA2NjAwMjkwMWU4ZDQyMDhhNzk2ZGU1ZjFmYSIsImlhdCI6MTY1NTQxNzU4Mn0.igoL2XGby69j-xcI3V-nUbjhoeICC10VBT5wAkJdrQw

{
  "disabled": false
}